grails-app/domain/intro/concepts/Account.groovy
package intro.concepts

// tag::AccountClass[]
class Account {
    String name
    Integer balance  // <1>

    static constraints = { }
}
// end::AccountClass[]

grails-app/domain/intro/concepts/Invoice.groovy
package intro.concepts

// tag::InvoiceClass[]
class Invoice {
    String name
    // <1>
    static hasMany = [items: Item]

    static constraints = { }
    // end::InvoiceClass[]

    // tag::InvoiceClassGetTotal[]
    def getTotal() {
      items.sum { it.amount }
    }
    // end::InvoiceClassGetTotal[]
}

grails-app/domain/intro/concepts/Item.groovy
package intro.concepts

// tag::ItemClass[]
class Item {
    String name
    Integer amount // <1>

    static constraints = { }
}
// end::ItemClass[]

grails-app/domain/intro/concepts/Person.groovy
package intro.concepts

class Person {
    // tag::PersonProperties[]
    String firstName        // <1>
    String lastName
    Boolean active = false  // <2>
    // end::PersonProperties[]
    // tag::PersonPropertiesEmail[]
    String emailAddress      // <1>
    // end::PersonPropertiesEmail[]


    static constraints = { // <3>
      // tag::PersonConstraints[]
      emailAddress nullable: true, email: true, unique: true // <3>
      // end::PersonConstraints[]
    }

    // tag::toString[]
    String toString() {
      firstName + " " + lastName
    }
    // end::toString[]

    // To illustrate command objects. We will use Spring-Security to manage users.
    def changePass(String password) {
      println "Changed password!"
      true
    }
}

grails-app/controllers/intro/concepts/AccountController.groovy
package intro.concepts

import grails.transaction.Transactional

// tag::AccountController[]
class AccountController {
    def accountService // <1>

    @Transactional(readOnly = true) // <2>
    def index() {
        render Account.list() // <3>
    }

    def show() { // <4>
        render accountService.get(params.long('id'))
    }

    def transfer() {
        def result = accountService.transfer(params.long('accountIdFrom'), params.long('accountIdTo'), params.int('amount'))

        render result
    }
}
// end::AccountController[]

grails-app/controllers/intro/concepts/ExampleController.groovy
package intro.concepts

class ExampleController {
  // tag::ExampleControllerIndex[]
  def index() {                               // <1>
    def myMap = [name: "Oliver", id: 123]     // <2>
    respond myMap                             // <3>
  }
  // end::ExampleControllerIndex[]

  // tag::ExampleControllerHello[]
  def hello() {
    def myMap = [greeting: "Hello ${params.name ?: 'world'}"]
    respond myMap
  }
  // end::ExampleControllerHello[]

  // tag::ExampleControllerSave[]
  def save(Person person) { // <1>
    if(!person.save()) {    // <2>
      respond person.errors // <3>
      return                // <4>
    }
    respond person          // <5>
  }
  // end::ExampleControllerSave[]

  // tag::tagLibs[]
  def tagLibs() {
    def bookList = [ books: [ // <1>
                      [id: 1, title: "Groovy In Action", price: 29_99],
                      [id: 2, title: "Java 8 In Action", price: 24_99]
                   ]]
    respond bookList
  }
  // end::tagLibs[]
}

grails-app/controllers/intro/concepts/PasswordController.groovy
// tag::PasswordController[]
package intro.concepts

class PasswordController {

  def update(PasswordCommand passwordCommand) {
    if(passwordCommand.validate()) {
      // Call a method to hash and save password
      passwordCommand.person.changePass(passwordCommand.password)
    } else {
      response.status = 400
      respond passwordCommand.errors
    }
  }
}

// Class in the same file as the Controller
class PasswordCommand {
  Person person          // <1>
  String password
  String retypePassword

  static constraints = { // <2>
    password minSize: 8
    retypePassword validator: { value, command ->
      if (command.password != command.retypePassword) {
          return 'passwordCommand.retypePassword.error.mismatch'
      }
    }
  }
}
// end::PasswordController[]

grails-app/controllers/intro/concepts/UrlMappings.groovy
package intro.concepts

class UrlMappings {

    static mappings = {
        "/$controller/$action?/$id?(.$format)?"{
            constraints {
                // apply constraints here
            }
        }

        "/"(view:"/index")
        "500"(view:'/error')
        "404"(view:'/notFound')
    }
}

grails-app/views/common/_bookTagLib.gsp
<div class='book'>
    <h2>${book.title}</h2>
    <book:price price="${book.price}"/> <!-- 1 -->
    <a href="<g:createLink controller="example" action="tagLibs" params="${[id: book.id]}"/>">BUY</a>
</div>

grails-app/views/common/_googleAnalytics.gsp
<!-- GA code here -->

grails-app/views/example/index.gsp
<html>
<head></head>
<body>
Model: ${name} <%= id %> <!-- 1 -->
</body>
</html>

grails-app/views/example/tagLibs.gsp
<g:each in="${books}" var="book">
    <book:display book="${book}"/>
</g:each>

grails-app/views/layouts/main.gsp
<!DOCTYPE html> // <1>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="${assetPath(src: 'favicon.ico')}" type="image/x-icon">

    <title><g:layoutTitle default="Default Site Title"/></title> // <2>
    <asset:stylesheet href="admin.css"/> // <3>
    <g:render template="/common/googleAnalytics"/> // <4>
    <g:layoutHead/> // <5>
</head>
<body>
<g:layoutBody/> // <6>

<asset:javascript src="admin.js"/> // <7>
<asset:deferredScripts/> // <8>
</body>
</html>